sudo: required
services:
  - docker

before_install:
  - docker build -t marc/docker-react -f Dockerfile.dev .

script:
  - docker run marc/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-3403243243294" //=S3 Storage where all the zip file from github is placed in
  bucket_path: "docker"  //same as app name
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

  //Docker-env.qqokfdks.us-west-2.elasticbeanstalk.com